apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongo-secret
  namespace: three-tier
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: mongo-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: mongo-db-secret
